### ISSUE TITLE
init-présentation

### ISSUE THREAD

**Issue by essarraj-fouad** [labs-web/lab-crud-basic-laravel#32]
# init-présentation
## Travail à faire
  - Élaboration d'un rapport sans contenu avec les  titres des diaspositive
  - Ajouter le lien du diaspositivedans le fichier index.md de le dossier docs
## Livrable
- docs/*
- backlog/sous-tache/init-presentation.md
- README.json
- README.md

**Comment by husseinbouik** [comment]
- la description de la tâche n'est pas valide

**Comment by essarraj-fouad** [comment]
Rapport n'est pas valide
