### ISSUE TITLE
init-lab

### ISSUE THREAD

**Issue by essarraj-fouad** [labs-web/lab-crud-basic-laravel#33]
# init-lab

## Travail à faire

- Élaboration d'un rapport sans contenu avec les titres des diaspositive

## Livrable

- docs/*
- backlog/sous-tache/init-rapport.16.md

**Comment by husseinbouik** [comment]
- la description de la tâche n'est pas valide

**Comment by essarraj-fouad** [comment]
Le rapport n'est pas valide
